first_project/adv_app/urls.py
from django.urls import path
from adv_app import views

app_name = "adv_app"

urlpatterns = [
    # path("", views.index, name="index"),
    path("", views.IndexView.as_view()),
]

first_project/first_project/urls.py
# from formsapp import views
from login_app import views
from django.contrib import admin
from django.urls import include, path

# from django.conf.urls import url


urlpatterns = [
    # url(r"^$", views.index, name="index"),
    path("", views.index, name="index"),
    path("formsapp/", include("formsapp.urls")),
    path("first_app/", include("first_app.urls")),
    path("basic_app/", include("basic_app.urls")),
    path("login_app/", include("login_app.urls")),
    path("adv_app/", include("adv_app.urls")),
    path("admin/", admin.site.urls),
]

first_project/login_app/urls.py
from django.urls import path
from login_app import views


app_name = "login_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.register, name="register"),
    path("user_login/", views.user_login, name="user_login"),
    path("logout/", views.user_logout, name="logout"),
]

first_project/login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional attributes

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to="profile_pics", blank=True)

    def __str__(self):
        return self.user.username

first_project/login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from login_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "email", "password")


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ("portfolio_site", "profile_pic")

first_project/login_app/views.py
from django.shortcuts import render
from login_app.forms import UserForm, UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.


def index(request):
    return render(request, "login_app/index.html")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("login_app:index"))


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if "profile_pic" in request.FILES:
                profile.profile_pic = request.FILES["profile_pic"]

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(
        request,
        "login_app/register.html",
        {
            "user_form": user_form,
            "profile_form": profile_form,
            "registered": registered,
        },
    )


def user_login(request):

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("login_app:index"))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("Someone tried to login and failed")
            print(f"Username: {username} and Password:{password}")
            return HttpResponse("INVALID CREDS!!!")

    else:
        return render(request, "login_app/login.html", {})

first_project/templates/login_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'login_app:index' %}">LOGIN APP</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:register' %}">Register</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:logout' %}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_app:user_login' %}">Log In</a>
                </li>
                {% endif %}


            </ul>

        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        <!--Anything outside this will be inherited on extending-->
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous">
    </script>
</body>

</html>

first_project/templates/login_app/index.html
{% extends 'login_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1 class="display-3">Django Login App</h1>
</div>

{% endblock body_block %}

first_project/templates/login_app/login.html
{% extends 'login_app/base.html' %}

{% block body_block %}

<div class="jumbotron">
    <h1 class="display-3">Please Login</h1>

    <form action="{% url 'login_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" id="" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" value="Submit" class="btn btn-primary">

    </form>
</div>

{% endblock body_block %}

first_project/templates/login_app/register.html
{% extends 'login_app/base.html' %}
{% load static %}
{% block body_block %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!!</h1>
    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register" class="btn btn-primary">
    </form>
    {% endif %}
</div>

{% endblock body_block %}