first_project/adv_app/urls.py
from django.urls import path
from adv_app import views

app_name = "adv_app"

urlpatterns = [
    # path("", views.index, name="index"),
    path("", views.IndexView.as_view()),
]

first_project/basic_app/urls.py
from basic_app import views
from django.urls import path

# TEMPLATE TAGGING
app_name = "basic_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("other/", views.other, name="other"),
    path("relative/", views.relative, name="relative"),
]

first_project/first_project/urls.py
# from formsapp import views
from login_app import views
from django.contrib import admin
from django.urls import include, path

# from django.conf.urls import url


urlpatterns = [
    # url(r"^$", views.index, name="index"),
    path("", views.index, name="index"),
    path("formsapp/", include("formsapp.urls")),
    path("first_app/", include("first_app.urls")),
    path("basic_app/", include("basic_app.urls")),
    path("login_app/", include("login_app.urls")),
    path("adv_app/", include("adv_app.urls")),
    path("admin/", admin.site.urls),
]

first_project/basic_app/views.py
from django.shortcuts import render


# Create your views here.


def index(request):
    context_dict = {"text": "hello world", "number": 100}
    return render(request, "basic_app/index.html", context_dict)


def other(request):
    return render(request, "basic_app/other.html")


def relative(request):
    return render(request, "basic_app/relative_url_template.html")

first_project/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'basic_app:index' %}">BRAND</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
                </li>
            </ul>

        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        <!--Anything outside this will be inherited on extending-->
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous">
    </script>
</body>

</html>

first_project/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load my_filters %}
{% block body_block %}
<h1>Welcome to Index</h1>
<h1>{{text}}</h1>
<h1>{{ text|upper }}</h1>
<h1>{{ text|cut:"hello" }}</h1>
<h1>{{ text|myCut:"world" }}</h1>
<h1>{{number}}</h1>
<h1>{{ number|add:"100" }}</h1>

{% endblock %}

first_project/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
<h1>Welcome to OTHER!!!</h1>
<h2>This is an example of template inheritance.</h2>
{% endblock %}

first_project/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Realtive URL</title>
</head>

<body>
    <h1>Welcome to relative url template</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">THE ADMIN PAGE</a>
</body>

</html>